# docker-compose.yml
version: '3.8'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - db
  migrate:
    build: .
    env_file:
      - ./.env
    depends_on:
      - db
    command: "/app/bin/migrate"
    restart: "no" 
  db:
    image: "postgres:14"
    restart: always
    environment:
      POSTGRES_DB: my_app_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" 

volumes:
  db_data: